name: SW_svile
author: svile
description: SkyWars plugin
main: svile\sw\SWmain
version: 0.7dev
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
load: STARTUP

commands:
 sw:
  description: SkyWars main command
